### ISSUE TITLE
Error reported when calling 'erbb build' on Max Reverb sample

### ISSUE THREAD

**Issue by sam-schorb** [ohmtech-rdi/eurorack-blocks#456]
When calling the `erbb build`  function, to create the firmware for the Max Reverb example, an error is reported.

```
clam@Clams-MacBook-Air reverb % erbb build
BUILD libDaisy
mkdir Release
ACTION Max
ACTION UI
ACTION Daisy
CXX src/detail/Debounce.cpp
CXX src/detail/Sram.cpp
CXX src/Button.cpp
CXX src/GateOut.cpp
CXX src/detail/Sdram.cpp
CXX main_daisy.cpp
CXX src/detail/Animation.cpp
CXX src/daisy/SubmoduleDaisySeed.cpp
CXX src/daisy/SubmoduleDaisyPatchSm.cpp
CXX module_max_alt.cpp
CXX include/gen_dsp/genlib.cpp
CXX Reverb_erbui.cpp
CXX Reverb_erbb.cpp
CC submodules/libDaisy/core/startup_stm32h750xx.c
LINK Release/Reverb.elf
/opt/homebrew/Cellar/arm-none-eabi-gcc/10.3-2021.07/gcc/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: Release/Users/clam/eurorack-blocks/max/reverb/artifacts/Reverb_erbui.cpp.o: in function `Reverb::perform()':
Reverb_erbui.cpp:(.text._ZN6Reverb7performEv+0x11e): undefined reference to `arm_sin_f32'
/opt/homebrew/Cellar/arm-none-eabi-gcc/10.3-2021.07/gcc/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: Reverb_erbui.cpp:(.text._ZN6Reverb7performEv+0x12a): undefined reference to `arm_cos_f32'
/opt/homebrew/Cellar/arm-none-eabi-gcc/10.3-2021.07/gcc/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: Reverb_erbui.cpp:(.text._ZN6Reverb7performEv+0x19c): undefined reference to `arm_sin_f32'
/opt/homebrew/Cellar/arm-none-eabi-gcc/10.3-2021.07/gcc/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: Reverb_erbui.cpp:(.text._ZN6Reverb7performEv+0x1a8): undefined reference to `arm_cos_f32'
/opt/homebrew/Cellar/arm-none-eabi-gcc/10.3-2021.07/gcc/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: Reverb_erbui.cpp:(.text._ZN6Reverb7performEv+0x21a): undefined reference to `arm_sin_f32'
/opt/homebrew/Cellar/arm-none-eabi-gcc/10.3-2021.07/gcc/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: Reverb_erbui.cpp:(.text._ZN6Reverb7performEv+0x226): undefined reference to `arm_cos_f32'
/opt/homebrew/Cellar/arm-none-eabi-gcc/10.3-2021.07/gcc/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: Reverb_erbui.cpp:(.text._ZN6Reverb7performEv+0x298): undefined reference to `arm_sin_f32'
/opt/homebrew/Cellar/arm-none-eabi-gcc/10.3-2021.07/gcc/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: Reverb_erbui.cpp:(.text._ZN6Reverb7performEv+0x2a4): undefined reference to `arm_cos_f32'
Memory region     Used Size Region Size %age Used
      FLASH:    80636 B    128 KB   61.52%
     DTCMRAM:     0 GB    128 KB   0.00%
      SRAM:    7764 B    512 KB   1.48%
     RAM_D2:    16968 B    288 KB   5.75%
     RAM_D3:     0 GB    64 KB   0.00%
     ITCMRAM:     0 GB    64 KB   0.00%
      SDRAM:     64 MB    64 MB  100.00%
    QSPIFLASH:     0 GB     8 MB   0.00%
collect2: error: ld returned 1 exit status
make: *** [Release/Reverb.elf] Error 1
Traceback (most recent call last):
 File "/Users/clam/eurorack-blocks/build-system/scripts/erbb", line 467, in <module>
  sys.exit (main ())
 File "/Users/clam/eurorack-blocks/build-system/scripts/erbb", line 431, in main
  build ()
 File "/Users/clam/eurorack-blocks/build-system/scripts/erbb", line 260, in build
  erbb.build_daisy_target (module, cwd, configuration)
 File "/Users/clam/eurorack-blocks/build-system/erbb/__init__.py", line 367, in build_daisy_target
  build_daisy_all (path, configuration)
 File "/Users/clam/eurorack-blocks/build-system/erbb/__init__.py", line 356, in build_daisy_all
  subprocess.check_call (cmd)
 File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
  raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '--jobs', '--directory=/Users/clam/eurorack-blocks/max/reverb/artifacts/daisy']' returned non-zero exit status 2.
clam@Clams-MacBook-Air reverb %
```

**Comment by ohmtech-rdi** [comment]
Thanks for the report @sam-schorb !

This is a regression that might occurred when switching from `gypi` files to make files. The CMSIS DSP, which contains fast math functions, is not compiled with `libDaisy` for good reasons, and we somehow forgot to include them when switching to Makefiles.
