### ISSUE TITLE
Issue when saving max patch under Windows

### ISSUE THREAD

**Issue by OmsInSerial** [ohmtech-rdi/eurorack-blocks#561]
Issue with node.script when saving max patcher under Windows. Here is the Max console output :  

```shell
node.script: artifacts already exists, skipping.
gen~: exported: C:/Users/xxxxx/eurorack-blocks/samples/test/artifacts/module_max.cpp
node.script: Build starting
node.script: module: /Users/xxxxx/eurorack-blocks/samples/test/
node.script: Configuring...
node.script: Error: python3: can't open file 'C:\\Users\\xxxxx\\OneDrive\\Documents\\Max 8\\build-system\\scripts\\erbb': [Errno 2] No such file or directory
node.script: child process exited with code 2
node.script: Building...
node.script: Error: python3: can't open file 'C:\\Users\\xxxxx\\OneDrive\\Documents\\Max 8\\build-system\\scripts\\erbb': [Errno 2] No such file or directory
node.script: child process exited with code 2

```

**Comment by ohmtech-rdi** [comment]
To be able to reproduce, I guess that in this case, the package was not added to max eg. https://github.com/ohmtech-rdi/eurorack-blocks/issues/556#issuecomment-1589268201

**Comment by ohmtech-rdi** [comment]
@OmsInSerial We used a different method to launch `erbb` in Max for Windows. It already landed on `main` could you please `git pull` the `main` branch and give it a go? Thanks!

**Comment by OmsInSerial** [comment]
```shell
xxxxx@xxxxx MINGW64 ~/eurorack-blocks (main)
$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   build-system/setup/__init__.py

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        samples/VCV/
        samples/test/

no changes added to commit (use "git add" and/or "git commit -a")
xxxxx@xxxxx MINGW64 ~/eurorack-blocks (main)
$ git pull
remote: Enumerating objects: 206, done.
remote: Counting objects: 100% (206/206), done.
remote: Compressing objects: 100% (104/104), done.
remote: Total 206 (delta 106), reused 174 (delta 98), pack-reused 0
Receiving objects: 100% (206/206), 188.67 KiB | 5.90 MiB/s, done.
Resolving deltas: 100% (106/106), completed with 18 local objects.
From https://github.com/ohmtech-rdi/eurorack-blocks
   073dfdc..7b8ff9a  main                   -> origin/main
 + 413dcc3...5d5f210 erbb-install-simulator -> origin/erbb-install-simulator  (forced update)
error: Your local changes to the following files would be overwritten by merge:
        build-system/setup/__init__.py
Please commit your changes or stash them before you merge.
Aborting
Updating 073dfdc..7b8ff9a
xxxxx@xxxxx MINGW64 ~/eurorack-blocks (main)
$ erbb setup
     --------------------------------------- 15.0/15.0 MB 50.4 MB/s eta 0:00:00
     -------------------------------------- 102.6/102.6 kB 5.8 MB/s eta 0:00:00
Extracting msys2_mingw64.zip...
Extracting kicad_minimal_windows_6.0.11-0.tar.gz...
Extracting gcc-arm-none-eabi-10.3-2021.10-win32.zip...
Installing python packages...
Optimizing erbb...
Checking toolchain...
OK.
``` 
Note that no path is added to Max after setup : 

![Sans titre2](https://github.com/ohmtech-rdi/eurorack-blocks/assets/76534228/2c2a7ab3-4b2a-4a98-a169-450e9acf9880)

Creating a fresh sample for Max :

```shell
xxxxx@xxxxx MINGW64 ~/eurorack-blocks/samples/test (main)
$ erbb init --name test --language max

``` 

Saving the sample in Max :

```shell
node.script: creating /Users/xxxxx/eurorack-blocks/samples/test/artifacts folder
gen~: exported: C:/Users/xxxxx/eurorack-blocks/samples/test/artifacts/module_max.cpp
node.script: Build starting
node.script: module: /Users/xxxxx/eurorack-blocks/samples/test/
node.script: Configuring...
node.script: Error: python3: can't open file 'C:\\Users\\xxxxx\\OneDrive\\Documents\\Max 8\\build-system\\scripts\\erbb': [Errno 2] No such file or directory
node.script: child process exited with code 2
node.script: Building...
node.script: Error: python3: can't open file 'C:\\Users\\xxxxx\\OneDrive\\Documents\\Max 8\\build-system\\scripts\\erbb': [Errno 2] No such file or directory
node.script: child process exited with code 2
``` 

Added this link :

```shell
xxxxx@xxxxx MINGW64 ~/OneDrive/Documents/Max 8
$ ln -s ~/eurorack-blocks/build-system/

``` 

Then saving again : 

```shell
node.script: creating /Users/xxxxx/eurorack-blocks/samples/test/artifacts folder
gen~: exported: C:/Users/xxxxx/eurorack-blocks/samples/test/artifacts/module_max.cpp
node.script: Build starting
node.script: module: /Users/xxxxx/eurorack-blocks/samples/test/
node.script: Configuring...
node.script: Error: Traceback (most recent call last):
  File "C:\Users\xxxxx\OneDrive\Documents\Max 8\build-system\scripts\erbb", line 605, in <module>
node.script: Error:     sys.exit (main ())
              ^^^^^^^
  File "C:\Users\xxxxx\OneDrive\Documents\Max 8\build-system\scripts\erbb", line 572, in main
    import erbb
  File "C:\Users\xxxxx\OneDrive\Documents\Max 8\build-system\erbb\__init__.py", line 42, in <module>
    import gyp
ModuleNotFoundError: No module named 'gyp'
node.script: child process exited with code 1
node.script: Building...
node.script: Error: Traceback (most recent call last):
  File "C:\Users\xxxxx\OneDrive\Documents\Max 8\build-system\scripts\erbb", line 605, in <module>
node.script: Error:     sys.exit (main ())
              ^^^^^^^
  File "C:\Users\xxxxx\OneDrive\Documents\Max 8\build-system\scripts\erbb", line 572, in main
    import erbb
  File "C:\Users\xxxxx\OneDrive\Documents\Max 8\build-system\erbb\__init__.py", line 42, in <module>
node.script: Error:     import gyp
ModuleNotFoundError: No module named 'gyp'
node.script: child process exited with code 1
``` 
Hope it'll help. Thanks

**Comment by ohmtech-rdi** [comment]
I think there was some sort of error when pulling:

```
error: Your local changes to the following files would be overwritten by merge:
        build-system/setup/__init__.py
Please commit your changes or stash them before you merge.
Aborting
```

**Comment by ohmtech-rdi** [comment]
But also there is another fix we didn't integrate yet, because this `ln -s` can't really work properly actually. @eliottparis is currently working on it.

So maybe let's postpone the test until this is integrated.

**Comment by ohmtech-rdi** [comment]
Ok, can you please:
```
git submodule update --init --recursive
```

Seems like gyp is missing for some reason.

**Comment by OmsInSerial** [comment]
```shell
xxxxx@xxxxx MINGW64 ~/eurorack-blocks (main)
$ git submodule update --init --recursive

``` 

Saving in Max, same error

```shell
node.script: artifacts already exists, skipping.
gen~: exported: C:/Users/xxxxx/eurorack-blocks/samples/test/artifacts/module_max.cpp
node.script: Build starting
node.script: module: /Users/xxxxx/eurorack-blocks/samples/test/
node.script: Configuring...
node.script: Error: Traceback (most recent call last):
  File "C:\Users\xxxxx\OneDrive\Documents\Max 8\build-system\scripts\erbb", line 614, in <module>
node.script: Error:     sys.exit (main ())
              ^^^^^^^
  File "C:\Users\xxxxx\OneDrive\Documents\Max 8\build-system\scripts\erbb", line 581, in main
node.script: Error:     import erbb
  File "C:\Users\xxxxx\OneDrive\Documents\Max 8\build-system\erbb\__init__.py", line 43, in <module>
node.script: Error:     from .generators.simulator.xcode import Xcode as simulatorXcode
  File "C:\Users\xxxxx\OneDrive\Documents\Max 8\build-system\erbb\generators\simulator\xcode.py", line 20, in <module>
node.script: Error:     import gyp
ModuleNotFoundError: No module named 'gyp'
node.script: child process exited with code 1
node.script: Building...
node.script: Error: Traceback (most recent call last):
  File "C:\Users\xxxxx\OneDrive\Documents\Max 8\build-system\scripts\erbb", line 614, in <module>
node.script: Error:     sys.exit (main ())
              ^^^^^^^
  File "C:\Users\xxxxx\OneDrive\Documents\Max 8\build-system\scripts\erbb", line 581, in main
node.script: Error:     import erbb
  File "C:\Users\xxxxx\OneDrive\Documents\Max 8\build-system\erbb\__init__.py", line 43, in <module>
node.script: Error:     from .generators.simulator.xcode import Xcode as simulatorXcode
  File "C:\Users\xxxxx\OneDrive\Documents\Max 8\build-system\erbb\generators\simulator\xcode.py", line 20, in <module>
node.script: Error:     import gyp
ModuleNotFoundError: No module named 'gyp'
node.script: child process exited with code 1

```

**Comment by ohmtech-rdi** [comment]
@OmsInSerial I think we need to pair on it. I'm reading and re-reading the code, and I have absolutely no idea how this could possibly not work. I'll contact you privately
