### ISSUE TITLE
ModuleNotFoundError: No module named 'gyp' in erbb configure

### ISSUE THREAD

**Issue by heuermh** [ohmtech-rdi/eurorack-blocks#662]
On osx, python 3.11 via pyenv, `erbb configure` fails for me when trying to configure the bypass example
```
(.venv) bypass main
$ erbb configure
Traceback (most recent call last):
  File "/Users/xxx/working/eurorack-blocks/build-system/scripts/erbb", line 797, in <module>
    sys.exit (main ())
              ^^^^^^^
  File "/Users/xxx/working/eurorack-blocks/build-system/scripts/erbb", line 761, in main
    import erbb
  File "/Users/xxx/working/eurorack-blocks/build-system/erbb/__init__.py", line 58, in <module>
    from .generators.simulator.xcode import Xcode as simulatorXcode
  File "/Users/xxx/working/eurorack-blocks/build-system/erbb/generators/simulator/xcode.py", line 20, in <module>
    import gyp
ModuleNotFoundError: No module named 'gyp'
```

**Comment by heuermh** [comment]
Fixed by properly initializing git submodules
```
$ git submodule init
Submodule 'submodules/gyp-next' (https://github.com/nodejs/gyp-next.git) registered for path 'submodules/gyp-next'
Submodule 'submodules/kicad-libs' (https://github.com/ohmtech/kicad-libs.git) registered for path 'submodules/kicad-libs'
Submodule 'submodules/libDaisy' (https://github.com/electro-smith/libDaisy.git) registered for path 'submodules/libDaisy'
Submodule 'submodules/vcv-rack-sdk' (https://github.com/ohmtech-rdi/vcv-rack-sdk.git) registered for path 'submodules/vcv-rack-sdk'

$ git submodule update
Cloning into '/Users/xxx/working/eurorack-blocks/submodules/gyp-next'...
Cloning into '/Users/xxx/working/eurorack-blocks/submodules/kicad-libs'...
Cloning into '/Users/xxx/working/eurorack-blocks/submodules/libDaisy'...
Cloning into '/Users/xxx/working/eurorack-blocks/submodules/vcv-rack-sdk'...
Submodule path 'submodules/gyp-next': checked out 'd83b0e5eb5d3cd63daf87e5ea056635ac2817ed8'
Submodule path 'submodules/kicad-libs': checked out 'd430194ecd07585e7c3b534c7cf26bd10cab9d7c'
Submodule path 'submodules/libDaisy': checked out 'b98d764d13ab3b7234f00d83a403714cb802c1be'
Submodule path 'submodules/vcv-rack-sdk': checked out '2088983c182f606e155bd67f632e799047bcbe7e'
```

Sorry for the noise!
