### ISSUE TITLE
max package installation

### ISSUE THREAD

**Issue by ManosDim** [ohmtech-rdi/eurorack-blocks#681]
`$ erbb setup --with-max-support
Extracting msys2_mingw64.zip...
Extracting kicad_minimal_windows_6.0.11-0.tar.gz...
Extracting gcc-arm-none-eabi-10.3-2021.10-win32.zip...
Adding Max support...
Traceback (most recent call last):
  File "C:\Users\eurorack-blocks\build-system\scripts\erbb", line 877, in <module>
    sys.exit (main ())
              ^^^^^^^
  File "C:\Users\eurorack-blocks\build-system\scripts\erbb", line 838, in main
    setup (args)
  File "C:\Users\eurorack-blocks\build-system\scripts\erbb", line 191, in setup
    setup.install_max_package ()
  File "C:\Users\eurorack-blocks\build-system\setup\__init__.py", line 550, in install_max_package
    max8_packages_path = os.path.join (path_documents (), 'Max 8', 'Packages')
                                       ^^^^^^^^^^^^^^^^^
  File "C:\Users\eurorack-blocks\build-system\setup\__init__.py", line 42, in path_documents
    import ctypes.wintypes
  File "C:\Lib\ctypes\__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ImportError: DLL load failed while importing _ctypes: %1 is not a valid Win32 application.
`

any fixes on this? i dont see the erb pack in the pack file of max too

**Comment by ohmtech-rdi** [comment]
Hi,

You could try to launch the Python interpreter and just do
```
>>> import ctypes.wintypes
```
And what it returns. `ctypes` is part of the Python Standard Library.

My guess is that [there could be something wrong with the Python installation](https://www.google.com/search?q=DLL+load+failed+while+importing+_ctypes%3A+%251+is+not+a+valid+Win32+application.) most likely a 32/64-bit conflict.
